<img src="../static/logopython.png" alt="Logo Python" style="width: 300px; display: inline"/>
<img src="../static/deimoslogo.png" alt="Logo Deimos" style="width: 300px; display: inline"/>

# Clase 09: Ejercicios prácticos

En esta clase vamos a afianzar los conocimientos de Python que acabamos de adquirir haciendo algunos ejercicios sobre numpy

In [2]:
# Importamos numpy para los ejercicios
import numpy as np

## Ejercicio 1:

Crear un array z1 3x4 lleno de ceros de tipo entero.

In [4]:
a = np.zeros((3, 4))
a

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

## Ejercicio 2

A partir del array anterior, crear un array z2 3x4 lleno de ceros salvo la primera fila que serán todo unos.

In [5]:
a[0, :] = 1
a

array([[ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

## Ejercicio 3

Crear un array z3 3x4 lleno de ceros salvo la última fila que será el rango entre 5 y 8.

__PISTA__: ¿Cómo se indexa la última fila de un array?

In [6]:
b = np.zeros((3, 4))
b[-1] = np.arange(5, 9)
b

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 5.,  6.,  7.,  8.]])

## Ejercicio 4

Crea un vector de 10 elementos, siendo los impares unos y los pares doses.

In [7]:
v = np.ones(10)
v[::2] = 2
v

array([ 2.,  1.,  2.,  1.,  2.,  1.,  2.,  1.,  2.,  1.])

## Ejercicio 5

Crea un «tablero de ajedrez», con unos en las casillas negras y ceros en las blancas.

In [17]:
tablero = np.zeros((8, 8))
tablero[1::2, ::2] = 1
tablero[::2, 1::2] = 1
tablero

array([[ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.]])

## Ejercicio 6

1. __Crea la matriz `B` 6x6__:

    \begin{pmatrix}
    1  & 2    &  4   &  8   & 16 &  32\\ 
    64 & 128  &  256 & ...  &     &   \\
    ... &     &      &      &     &   \\
    ... &     &      &      &     &   \\
    ... &     &      &      &     &   \\
    ... &     &      &      &     &   \\
    \end{pmatrix}
    
    Créala usando un bucle primero y luego una expresión más *pythonica*.
    
    __Pista__: Una expresión de tipo *comprehension list* y la función *reshape* te pueden ayudar
    
    
2.  __Calcula el determinante de `B`__.

In [4]:
B = np.array([2 ** i for i in range(36)]).reshape((6,6))

B

array([[          1,           2,           4,           8,          16,
                 32],
       [         64,         128,         256,         512,        1024,
               2048],
       [       4096,        8192,       16384,       32768,       65536,
             131072],
       [     262144,      524288,     1048576,     2097152,     4194304,
            8388608],
       [   16777216,    33554432,    67108864,   134217728,   268435456,
          536870912],
       [ 1073741824,  2147483648,  4294967296,  8589934592, 17179869184,
        34359738368]])

In [9]:
np.linalg.det(B)

0.0

## Ejercicio 7

3. __Crea la matriz `C`:__

    \begin{pmatrix}
    1  & 2  &  4  \\ 
    6  & 5  &  8  \\
    2  & 2  &  11 \\
    \end{pmatrix}
    
3.  __Inviértela creando `C_inv`__.

In [10]:
C =  np.array([[1,2,4],\
               [6,5,8],\
               [2,2,11]])

In [11]:
np.linalg.det(C)

C_inv = np.linalg.inv(C)
print(C_inv)

C_inv.dot(C)

[[-0.73584906  0.26415094  0.0754717 ]
 [ 0.94339623 -0.05660377 -0.30188679]
 [-0.03773585 -0.03773585  0.13207547]]


array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [ -1.11022302e-16,   1.00000000e+00,   0.00000000e+00],
       [  5.55111512e-17,   0.00000000e+00,   1.00000000e+00]])

## Ejercicio 8

Hallar el producto de estas dos matrices y su determinante:

$$\begin{pmatrix} 1 & 0 & 0 \\ 2 & 1 & 1 \\ -1 & 0 & 1 \end{pmatrix} \begin{pmatrix} 2 & 3 & -1 \\ 0 & -2 & 1 \\ 0 & 0 & 3 \end{pmatrix}$$

__Pista__: Te puede interesar revisar el módulo de álgebra lineal incluído en numpy para encontrar funciones que te ayuden a hacer las operaciones pedidas

```python
help(np.linalg)```

In [12]:
from numpy.linalg import det

A = np.array([
    [1, 0, 0],
    [2, 1, 1],
    [-1, 0, 1]
])
B = np.array([
    [2, 3, -1],
    [0, -2, 1],
    [0, 0, 3]
])

print(A)
print(B)

C = np.dot(A, B)
print(C)

det(C)

[[ 1  0  0]
 [ 2  1  1]
 [-1  0  1]]
[[ 2  3 -1]
 [ 0 -2  1]
 [ 0  0  3]]
[[ 2  3 -1]
 [ 4  4  2]
 [-2 -3  4]]


-12.0

## Ejercicio 9

Resolver el siguiente sistema:

$$ \begin{pmatrix} 2 & 0 & 0 \\ -1 & 1 & 0 \\ 3 & 2 & -1 \end{pmatrix} \begin{pmatrix} 1 & 1 & 1 \\ 0 & 1 & 2 \\ 0 & 0 & 1 \end{pmatrix} \begin{pmatrix} x \\ y \\ z \end{pmatrix} = \begin{pmatrix} -1 \\ 3 \\ 0 \end{pmatrix} $$

__Pista__: Te puede interesar revisar el módulo de álgebra lineal incluído en numpy para encontrar funciones que te ayuden a hacer las operaciones pedidas

In [13]:
M = np.dot(
np.array([
    [2, 0, 0],
    [-1, 1, 0],
    [3, 2, -1]
]),
np.array([
    [1, 1, 1],
    [0, 1, 2],
    [0, 0, 1]
]))
M

array([[ 2,  2,  2],
       [-1,  0,  1],
       [ 3,  5,  6]])

In [14]:
x = np.linalg.solve(M, np.array([-1, 3, 0]))
x

array([ 0.5, -4.5,  3.5])

In [3]:
# Esta celda da el estilo al notebook
from IPython.core.display import HTML
css_file = '../static/styles/style.css'
HTML(open(css_file, "r").read())